title = "Zoltan Toma"
languageCode = "en-us"
#theme = "cactus"
baseURL = "https://zoltantoma.com/"
enableRobotsTXT = false # permission issue on site generatation. TODO: check it.
copyright = "Zoltan Toma"
disqusShortname = "zoltantoma"
[params]
  colortheme = "dark" # dark
  description = "As a passionate Security Software Engineer with a decade’s experience, my mission is to make the digital world safer. Leveraging open-source technologies, I specialize in developing innovative cybersecurity solutions and promoting cybersecurity awareness. My approach combines technical expertise with a commitment to community education, aiming to empower others with the knowledge to protect themselves online. I’m looking for opportunities where I can apply my skills in Go, cloud security, and DevSecOps to not only address current security challenges but also to inspire and lead in the creation of safer digital environments for everyone.\n\nMy current project is to discover the relationship between Mental Health and the Cyber World with shorter content, which I refer to as #MentalInCyber. Are we capable of living in the cyber age? Let's find out together.\n\nUnfortunately, being enthusiastic and creating content is not enough. This requires much more diverse solutions, which is why I mark these efforts and results with #TheMetaGame. For example, owning an Estonian company enables me to help you more flexiblely.\n\nWant to know more? Schedule time with me at https://calendly.com/zoltantoma87/one-on-one"
  author = "Zoltan Toma"
  showVisitedLinks = true
  collapsibleMenu = false
  disableBreadcrumb = false
  disableNextPrev = false
  mainSection = "blog"
  # cactus
  showAllPostsOnHomePage = true
  showAllPostsArchive = true
  postsOnHomePage = 10
  rss = true
  tagsOverview = false
  showProjectsList = true
  css = ["css/custom.css"]

[params.comments]
    enabled = false # default
    engine = "disqus"
  
[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/toma-zoltan/"
[[params.social]]
  name = "github"
  link = "https://github.com/LeeShan87"
[[params.social]]
    name = "youtube"
    link = "https://youtube.com/@zoltantoma"
[[params.social]]
  name = "twitter"
  link = "https://twitter.com/@ZoltanToma_"

# GoSecNinja's availablilities
[[params.social]]
    name = "youtube"
    link = "https://youtube.com/@gosecninja"
[[params.social]]
  name = "twitter"
  link = "https://twitter.com/GoSecNinja"
[[params.social]]
  name = "email"
  link = "zoltantoma@gosec.ninja"  # no need for "mailto:" in the head
  
[markup]
  [markup.highlight]
    guessSyntax = true

    #noClasses = false
    style = "github-dark"

  [markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    #path = "gitlab.com/gabmus/hugo-ficurinia"
    path = "github.com/monkeyWzr/hugo-theme-cactus"
    disable = false

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

  [[menu.main]]
  name = "Notes"
  url = "https://notes.zoltantoma.com"
  weight = 4

  [[menu.main]]
  name = "Gear"
  url = "/gear"
  weight = 7

  [[menu.main]]
  name = "CV"
  url = "/cv"
  weight = 10

  
#  [[menu.main]]
#  name = "Tags"
#  url = "/tags"
#  weight = 3

  